# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
orbs:
  slack: circleci/slack@4.2.0
version: 2.1
executors:
  app-executor:
    docker:
      - image: circleci/node:14.17.6
    working_directory: ~/repo
  slack-executor:
    docker:
      - image: "cibuilds/base:latest"
    resource_class: small

aliases:
  - &show-current-branch-name
    run:
      name: show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{checksum "package.json"}}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{checksum "package.json"}}
  - &install-aws-cli
    run:
      name: Installing AWS CLI
      working_directory: /
      command: |
        sudo apt-get -y -qq update
        sudo apt-get install -y awscli
        sudo apt-get install -y python-pip python-dev build-essential
  - &build-project
    run:
      name: Build Project
      command: |
        npm install
        npm run build
        cd build
        zip ../build.zip -r * .[^.]*
        echo "Build successful"

jobs:
  # Initial installations and checks.
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache
  # Es-lint
  linting:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run linting
          command: npm run lint
  # Prettier
  prettier:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run prettier
          command: npm run prettier:check
  # Deploy.
  deploy-to-aws-s3:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *install-aws-cli
      - *build-project
      # deploy to aws s3
      - run:
          name: Deploy to aws s3
          command: |
            if ["${CIRCLE_BRANCH}" == "master"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_PRODUCTION} --delete
            elif ["${CIRCLE_BRANCH}" == "develop"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_DEV_BUCKET} --delete
            else
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_STAGING} --delete
            fi
    test:
      executor: app-executor
      steps:
        - run: echo "test my app"

    notify-via-slack:
      executor: slack-executor
      steps:
        - run: echo "Slack notification"
        - slack/notify:
            event: "always"
            channel: "film-app-automation"
            template: ""
            custom: |
              {
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "${CIRCLE_BRANCH} branch deployment to aws s3 and cloudfront is complete.👍",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                      },
                       {
                        "type": "mrkdwn",
                        "text": "*Branch*:\n$CIRCLE_BRANCH"
                      },
                       {
                        "type": "mrkdwn",
                        "text": "*When*:\n$(date + '%m/%d/%Y %T')"
                      },
                       {
                        "type": "mrkdwn",
                        "text": "*Build*:\n$CIRCLE_BUILD_NUM"
                      },
                       {
                        "type": "mrkdwn",
                        "text": "*Author*:\n$CIRCLE_PROJECT_USERNAME"
                      }
                    ]
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Go to job details"
                        },
                        "url": "${CIRCLE_BUILD_URL}"
                      }
                    ]
                  }
                ]
              }

  # Cloudfront.
  deploy-to-aws-cloudfront:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *install-aws-cli
      - *build-project
      # deploy to aws cloudfront
      - run:
          name: Deploy to aws Cloudfront
          command: |
            aws configure set preview.cloudfront true
            if ["${CIRCLE_BRANCH}" == "master"]
            then
              aws cloudfront create-invalidation --distribution-id ${PRODUCTION_DISTRIBUTION_ID} --path /\*
            elif ["${CIRCLE_BRANCH}" == "staging"]
            then
              aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --path /\*
            else
              aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --path /\*
            fi

  # workflow, implements jobs to run in what order
workflows:
  build_and_deploy:
    jobs:
      - test
      - notify-via-slack:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      # - prettier:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - staging
      #           - master
      # - deploy-to-aws-s3:
      #     requires:
      #       - prettier
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - staging
      #           - master
      # - deploy-to-aws-cloudfront:
      #     requires:
      #       - deploy-to-aws-s3
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - staging
      #           - master
      # - notify-via-slack:
      #     requires:
      #       - deploy-to-aws-cloudfront
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - staging
      #           - master
